### ISSUE TITLE
发现的一些小bug

### ISSUE THREAD

**Issue by JoeCqupt** [wosyingjun/beauty_ssm#12]
首先购买的操作controller  goods/**/buy RequestMapping的method应该改为RequestMethod.POST。其次购买成功后的删除缓存操作 cache.deleteCacheWithPattern("getGoodsList")失效问题。 应该改为cache.deleteCacheWithPattern(cache.CAHCENAME+"|getGoodsList*");

**Comment by RookieTester** [comment]
哈哈，第一个不知道是作者故意的还是失误。

**Comment by dianxiaopao** [comment]
cache.deleteCacheWithPattern("getGoodsList")这个无效
cache.deleteCacheWithPattern(cache.CAHCENAME+"|getGoodsList*");这个也不行，都要等好久才能清除

**Comment by 449073709** [comment]
我想问的是为什么“/beauty_ssm/goods/1000/buy”是POST请求而不是GET请求

**Comment by jin2clear** [comment]
一般来讲，够买这种操作属于提交数据，固然你可以使用GET，但是从业内规范来讲，GET只用于获取数据，POST用于向服务器提交数据，查询商品用GET是没问题的，买东西的话还是使用POST比较合理
